---
title: "Impacts of Major Natural Disasters on American Communities"
author: "Alyssa Girard, Akillesh Suresh, Kaya Williams"
date: "2025-12-11"
output: html_document
toc: yes
theme: cerulean
code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE)

library(tidyverse)
library(here)
library(dplyr)
library(treemapify)
library(ggpmisc)
library(ggplot2)
library(tigris)
library(viridis)
library(scales)
library(grid)
library(lubridate)
library(sf)
```

## Introduction
### How Do Hurricanes, Wildfires, and Floods Affect Human Welfare and Economics in the United States?

## Data & Data Sources
### Natural Disasters: Our World in Data
- Our first data source is from Our World in Data's Natural Disasters dataset
- It contains data from multiple types of disasters and impacts (e.g., deaths, injuries, homeless, et cetera) and the year the disaster occurred.
- We believe this data source is valid, because Our World In Data gets their data from valid sources, listed on their website as "international institutions and statistical agencies, such as the OECD, the World Bank, the WHO, and UN institutions, specialized institutes and think tanks, such as the Peace Research Institute Oslo (PRIO), academic research articles, such as Bourguignon & Morrison (2002) ’Inequality Among World Citizens: 1820-1992’ in the American Economic Review, and official data from government sources."
- Link: https://ourworldindata.org/natural-disasters#explore-data-on-natural-disasters

### Losses from Natural Disasters: Federal Reserve Bank of New York
- Our second data source is the Federal Reserve Bank of New York's Losses from Natural Disasters, which describes the direct damages from natural disasters across the United States by county.
- We believe this data source is valid because it is from a federal resource, specifically the Federal Reserve Bank of New York.
- Link: https://www.newyorkfed.org/research/policy/natural-disaster-losses/#interactive

### A Weekly Influenza Surveillance Report: CDC
- Our third data source is the CDC's Weekly Influenze Surveillance Report, which tracks the level of visits for respiratory illness.
- We believe this source is valid because it comes directly from the Center of Disease Control, a government organization.
- Link: https://gis.cdc.gov/grasp/fluview/main.html


## Results
### How do rates of respiratory symptoms change after natural disasters?


## Conclusion

## Contributions
### Kaya Williams
- 

### Akillesh Suresh
- 

### Alyssa Girard
- 