---
title: "regions affected"
author: "Akillesh Suresh"
date: "2025-11-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)
```


```{r}
library(tidyverse)
library(sf)
library(tigris)
library(here)
library(viridis)
library(scales)
library(grid)

losses <- read_csv(here("data/NYFed_natural-disasters_download_data/lnd_full_clean_2024-12-31.csv"))

losses <- losses %>%
  mutate(fips = str_pad(fips, width = 5, side = "left", pad = "0")) %>%
  filter(damages_total_adj > 0)

major_types <- c(
  "Flood", "Flash Flood", "Hurricane", "Tropical Storm",
  "Storm Surge/Tide", "Tornado", "Wildfire", "High Wind",
  "Winter Storm", "Thunderstorm Wind"
)

losses_major <- losses %>%
  filter(event_type %in% major_types)

# NEW: Damage aggregation
county_damage <- losses_major %>%
  group_by(fips) %>%
  summarize(total_damage = sum(damages_total_adj, na.rm = TRUE))

map_data <- counties %>%
  left_join(county_damage, by = c("GEOID" = "fips"))

map_data$total_damage[is.na(map_data$total_damage)] <- 0

```

```{r, fig.width=14, fig.height=10}
ggplot(map_data) +
  geom_sf(aes(fill = total_damage), color = NA) +
  scale_fill_viridis_c(
    option = "A",
    trans = "log10",
    labels = scales::label_number(
      accuracy = 0.1,
      scale_cut = scales::cut_short_scale()
    )
  ) +
  labs(
    title = "Total Natural Disaster Damage by County",
    subtitle = "Cumulative inflation-adjusted damage from major hazard events",
    fill = "Total Damage"
  ) +
  coord_sf(
    xlim = c(-125, -65),
    ylim = c(25, 50),
    expand = FALSE
  ) +
  theme_minimal(base_size = 16) +
  theme(
    legend.position = "bottom",
    legend.key.width = unit(4, "cm"),
    legend.key.height = unit(0.7, "cm"),
    panel.grid = element_blank()
  )
```

